# This workflow will do a clean install of java, analyze the source
# code for vulnerabilities and upload results to CoPilot
# For more information see: https://copilot.blackducksoftware.com/

name: blackduck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [1.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java (CoPilot)
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Upload to CoPilot
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
